## Base model 생성

In [1]:
## 모듈 임포트
from sklearn.model_selection import train_test_split  ## train test 

from sklearn.linear_model import LinearRegression   ## 회귀 분석
from sklearn.linear_model import LogisticRegression ## Logistic Regression
from sklearn.ensemble import RandomForestRegressor  ## RandomForet

import lightgbm as lgb
from sklearn.multioutput import MultiOutputRegressor  ## MultiOutputRegressor

from sklearn.metrics import accuracy_score     ## 정확도 검증

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# 데이터 로드
test_data2 = pd.read_csv('C:/Users/admin/Desktop/개별1/data/test2.csv')
train_data2 = pd.read_csv('C:/Users/admin/Desktop/개별1/data/train2.csv')
sample_data = pd.read_csv('C:/Users/admin/Desktop/개별1/data/sample_submission.csv')

In [4]:
test_data = pd.read_csv('C:/Users/admin/Desktop/개별1/data/test.csv')
train_data = pd.read_csv('C:/Users/admin/Desktop/개별1/data/train.csv')

In [5]:
## train, test set 설정

train_X = train_data.iloc[:,4:]
train_Y = train_data.iloc[:,0:4]
test_X = test_data.iloc[:,1:]

In [14]:
train_X.head()

0         1         2         3         4         5         6  \
0  0.254551  0.258823  0.254659  0.252085  0.247678  0.253614  0.246511   
1  0.205062  0.225544  0.217758  0.202169  0.199633  0.207380  0.191318   
2  0.189196  0.165869  0.177655  0.156822  0.175094  0.177755  0.157582   
3  0.131003  0.120076  0.138975  0.117931  0.130566  0.131262  0.126962   
4  0.091033  0.086893  0.108125  0.080405  0.105917  0.077083  0.097895   

          7         8         9  ...       216       217       218       219  \
0  0.259407  0.260862  0.242524  ...  0.354750  0.369223  0.388184  0.408496   
1  0.195369  0.200536  0.197588  ...  0.557203  0.573656  0.587998  0.612754   
2  0.158885  0.156911  0.166162  ...  0.699864  0.708688  0.721982  0.713464   
3  0.134453  0.106717  0.127309  ...  0.764786  0.763788  0.770017  0.787571   
4  0.086765  0.078676  0.075729  ...  0.786677  0.802271  0.806557  0.799614   

        220       221       222       223       224       225  
0  0.414564  0.429403  0.419225  0.443250  0.433414  0.465502  
1  0.627825  0.633393  0.637706  0.625981  0.653231  0.637853  
2  0.743030  0.741709  0.747743  0.746037  0.737356  0.750391  
3  0.778866  0.776969  0.774712  0.801526  0.805305  0.784057  
4  0.789333  0.804087  0.787763  0.794948  0.819105  0.801781  

[5 rows x 226 columns]

In [15]:
train_Y.head()

layer_1  layer_2  layer_3  layer_4
0       10       10       10       10
1       10       10       10       20
2       10       10       10       30
3       10       10       10       40
4       10       10       10       50

In [18]:
test_X.head()

0         1         2         3         4         5         6  \
0  0.535410  0.520775  0.494087  0.465134  0.430339  0.401751  0.355986   
1  0.351099  0.398179  0.413809  0.418529  0.433257  0.455410  0.451065   
2  0.490537  0.435958  0.413428  0.355796  0.335777  0.299944  0.242745   
3  0.051634  0.075802  0.133983  0.154546  0.209387  0.251700  0.287552   
4  0.154031  0.201728  0.270414  0.283799  0.343050  0.340233  0.379244   

          7         8         9  ...       216       217       218       219  \
0  0.326427  0.282340  0.216756  ...  0.748339  0.757575  0.768130  0.777062   
1  0.464230  0.476011  0.477219  ...  0.333931  0.276307  0.211513  0.159223   
2  0.210555  0.180739  0.169717  ...  0.709371  0.746826  0.781436  0.788292   
3  0.333000  0.340617  0.393592  ...  0.075046  0.056651  0.079884  0.147469   
4  0.378511  0.373017  0.364702  ...  0.255070  0.242396  0.271287  0.328828   

        220       221       222       223       224       225  
0  0.769173  0.768253  0.738704  0.739460  0.702139  0.702238  
1  0.110982  0.083130  0.099780  0.145420  0.260501  0.343857  
2  0.828630  0.835166  0.845859  0.846032  0.836724  0.846779  
3  0.213112  0.298096  0.382823  0.489381  0.562383  0.599247  
4  0.397950  0.486436  0.530573  0.582752  0.637296  0.637238  

[5 rows x 226 columns]

In [6]:
lr = LinearRegression()
model = lgb.LGBMRegressor()
mor = MultiOutputRegressor(model)

In [7]:
# LinearRegression 결과

lr.fit(train_X, train_Y)
lr.score(train_X, train_Y)

0.016982162376515703

In [8]:
# MultiOutputRegressor 결과

mor.fit(train_X, train_Y)
mor.score(train_X, train_Y)

0.4456092977489152

## 음수 처리 후

In [9]:
## train, test set 설정

train_X = train_data2.iloc[:,4:]
train_Y = train_data2.iloc[:,0:4]
test_X = test_data2.iloc[:,1:]
test_Y = sample_data.iloc[:,1:]

In [10]:
## 모델 생성

lr = LinearRegression()
model = lgb.LGBMRegressor()
mor = MultiOutputRegressor(model)

In [11]:
# LinearRegression 결과

lr.fit(train_X, train_Y)
lr.score(train_X, train_Y)

0.01707591187915211

In [12]:
lr_y_preds = lr.predict(test_X)
lr_y_preds

array([[157.20621621, 150.72990744, 160.66644905, 128.10206544],
       [164.10766711, 152.79130847, 163.22790159, 163.56063056],
       [145.46272158, 153.48905131, 156.4262556 , 133.28413278],
       ...,
       [144.90898784, 158.46420108, 148.33675488, 160.64440435],
       [145.96971777, 160.39291815, 152.11176244, 185.8683756 ],
       [156.26051752, 170.65030331, 151.71630938, 207.50052979]])

In [17]:
# MultiOutputRegressor 결과

mor.fit(train_X, train_Y)
mor.score(train_X, train_Y)

0.44343734945399443

In [19]:
mor_y_preds = mor.predict(test_X)
mor_y_preds

array([[226.83295111, 200.06059893, 178.27941502, 130.01457194],
       [127.75749124, 145.05996415, 197.09375601, 127.01076159],
       [194.08164104, 170.95428633, 240.8348393 , 144.2489526 ],
       ...,
       [100.46899304, 166.33201976, 189.91331168, 156.05877885],
       [ 91.14505989, 100.11456214,  84.20675421, 145.49143079],
       [ 89.26104936, 109.13362355,  65.56431095, 110.13449309]])

In [20]:
sample_data['layer_1'] = mor_y_preds[:,0]
sample_data['layer_2'] = mor_y_preds[:,1]
sample_data['layer_3'] = mor_y_preds[:,2]
sample_data['layer_4'] = mor_y_preds[:,3]

In [21]:
mor_layer_pre = sample_data

In [22]:
mor_layer_pre

id     layer_1     layer_2     layer_3     layer_4
0        0  226.832951  200.060599  178.279415  130.014572
1        1  127.757491  145.059964  197.093756  127.010762
2        2  194.081641  170.954286  240.834839  144.248953
3        3  127.213469  170.942078  138.932526  179.465021
4        4  254.381349  240.750451  204.456977  227.244964
...    ...         ...         ...         ...         ...
9995  9995  114.296193  110.511561   55.158622  100.153785
9996  9996  125.110780  130.975162  144.352078   95.775712
9997  9997  100.468993  166.332020  189.913312  156.058779
9998  9998   91.145060  100.114562   84.206754  145.491431
9999  9999   89.261049  109.133624   65.564311  110.134493

[10000 rows x 5 columns]

In [ ]:
mor_layer_pre.to_csv('C:/Users/admin/Desktop/개별1/data/mor_layer_m.csv', header=['id','layer_1','layer_2','layer_3','layer_4'], index=False)

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
# DecisionTreeRegressor 결과

dr = DecisionTreeRegressor()
dr.fit(train_X, train_Y)
dr.score(train_X, train_Y)

## StandardScaler

In [23]:
from sklearn.preprocessing import StandardScaler

standardscaler = StandardScaler()

In [25]:
standardscaler.fit(train_X)

StandardScaler()

In [26]:
train_X_scaled = standardscaler.transform(train_X)

In [27]:
train_X_scaled

array([[-0.21146564, -0.18901868, -0.2130855 , ..., -0.95524602,
        -1.01880781, -0.86781448],
       [-0.4844602 , -0.37238127, -0.41620128, ..., -0.01558695,
         0.11358578,  0.02193628],
       [-0.57198424, -0.70118139, -0.63693977, ...,  0.60177912,
         0.54695651,  0.60290247],
       ...,
       [-0.19803518, -0.31313521, -0.59367687, ..., -0.09429971,
        -0.62549773, -1.28969276],
       [-0.4366491 , -0.63979508, -0.92241466, ..., -1.89933498,
        -2.45957149, -2.60239403],
       [-0.81428408, -1.09338757, -1.23769394, ..., -2.0863753 ,
        -1.44686994, -0.68946718]])

In [28]:
train_X_scaled = pd.DataFrame(train_X_scaled)

In [30]:
# MultiOutputRegressor 결과

mor.fit(train_X_scaled, train_Y)
mor.score(train_X_scaled, train_Y)

0.4442751879563733